name: ul-transxnet
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - pillow
  - matplotlib
  - pytorch
  - torchvision
  - pip
  - pip:
      - timm
      - ultralytics
      - opencv-python
      - cairosvg
