from __future__ import annotations

import csv
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
COMPLEXITY_CSV = PROJECT_ROOT / "eval_reports" / "paper_model_complexity_table.csv"
LATENCY_CSV = PROJECT_ROOT / "eval_reports" / "tn5000_local_latency" / "tn5000_local_latency_latest.csv"
OUT_CSV = PROJECT_ROOT / "eval_reports" / "paper_complexity_performance_tradeoff.csv"
OUT_TEX = PROJECT_ROOT / "eval_reports" / "paper_complexity_performance_tradeoff.tex"


METHOD_INFO = {
    "ResNet50": {"type": "CNN", "tn_auc": 0.6531, "busi_auc": 0.7519, "aul_auc": 0.5481, "mean_balacc": 0.6190},
    "DenseNet121": {"type": "CNN", "tn_auc": 0.9360, "busi_auc": 0.8154, "aul_auc": 0.6729, "mean_balacc": 0.7401},
    "EfficientNet-B0": {"type": "Efficient CNN", "tn_auc": 0.7856, "busi_auc": 0.7659, "aul_auc": 0.6099, "mean_balacc": 0.6682},
    "MobileNetV3-Large": {"type": "Mobile CNN", "tn_auc": 0.8282, "busi_auc": 0.7947, "aul_auc": 0.7357, "mean_balacc": 0.7183},
    "Swin-T": {"type": "Transformer", "tn_auc": 0.9497, "busi_auc": 0.8190, "aul_auc": 0.8319, "mean_balacc": 0.7901},
    "ConvNeXt-Tiny": {"type": "ConvNet", "tn_auc": 0.9508, "busi_auc": 0.8050, "aul_auc": 0.8274, "mean_balacc": 0.7651},
    "RepViT-M1.1": {"type": "Mobile CNN", "tn_auc": 0.8403, "busi_auc": 0.8028, "aul_auc": 0.6797, "mean_balacc": 0.7020},
    "EfficientFormer-L1": {"type": "Hybrid", "tn_auc": 0.9249, "busi_auc": 0.7917, "aul_auc": 0.7196, "mean_balacc": 0.7330},
    "UL-TransXNet": {"type": "Ours", "tn_auc": 0.9483, "busi_auc": 0.8998, "aul_auc": 0.8767, "mean_balacc": 0.8296},
}


ORDER = [
    "MobileNetV3-Large",
    "EfficientNet-B0",
    "EfficientFormer-L1",
    "RepViT-M1.1",
    "UL-TransXNet",
    "DenseNet121",
    "ResNet50",
    "ConvNeXt-Tiny",
    "Swin-T",
]


def load_complexity() -> dict[str, dict[str, str]]:
    with COMPLEXITY_CSV.open("r", encoding="utf-8") as f:
        return {row["method"]: row for row in csv.DictReader(f)}


def load_latency() -> dict[str, dict[str, str]]:
    if not LATENCY_CSV.exists():
        return {}
    with LATENCY_CSV.open("r", encoding="utf-8") as f:
        return {row["method"]: row for row in csv.DictReader(f)}


def fmt(v: float) -> str:
    return f"{v:.4f}"


def bold_if_best(method: str, value: str, best_method: str) -> str:
    return f"\\textbf{{{value}}}" if method == best_method else value


def build_rows() -> list[dict[str, object]]:
    complexity = load_complexity()
    latency = load_latency()
    rows = []
    for method in ORDER:
        info = METHOD_INFO[method]
        cx = complexity[method]
        lat = latency.get(method, {})
        mean_auc = (info["tn_auc"] + info["busi_auc"] + info["aul_auc"]) / 3.0
        rows.append(
            {
                "method": method,
                "type": info["type"],
                "input": cx["input"],
                "params_m": float(cx["params_m"]),
                "macs_g": float(cx["macs_g"]),
                "cuda_ms": float(lat["model_mean_ms"]) if lat else float("nan"),
                "cuda_fps": float(lat["model_fps"]) if lat else float("nan"),
                "tn_auc": info["tn_auc"],
                "busi_auc": info["busi_auc"],
                "aul_auc": info["aul_auc"],
                "mean_auc": mean_auc,
                "mean_balacc": info["mean_balacc"],
            }
        )
    return rows


def write_csv(rows: list[dict[str, object]]) -> None:
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with OUT_CSV.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        for row in rows:
            out = dict(row)
            for key in ("params_m", "macs_g", "cuda_ms", "cuda_fps", "tn_auc", "busi_auc", "aul_auc", "mean_auc", "mean_balacc"):
                if key in ("tn_auc", "busi_auc", "aul_auc", "mean_auc", "mean_balacc"):
                    out[key] = f"{float(out[key]):.4f}"
                elif key == "cuda_fps":
                    out[key] = f"{float(out[key]):.1f}"
                else:
                    out[key] = f"{float(out[key]):.2f}"
            writer.writerow(out)


def write_tex(rows: list[dict[str, object]]) -> None:
    best_mean_auc = max(rows, key=lambda r: float(r["mean_auc"]))["method"]
    best_mean_balacc = max(rows, key=lambda r: float(r["mean_balacc"]))["method"]
    best_tn = max(rows, key=lambda r: float(r["tn_auc"]))["method"]
    best_busi = max(rows, key=lambda r: float(r["busi_auc"]))["method"]
    best_aul = max(rows, key=lambda r: float(r["aul_auc"]))["method"]
    lines = [
        "% Auto-generated by tools/make_complexity_performance_table.py",
        "\\begin{table*}[t]",
        "    \\centering",
        "    \\small",
        "    \\caption{Complexity--performance trade-off of the finalized comparison pool. CUDA latency is the mean model-only batch-1 latency measured on the local workstation; AUC values are mean test AUCs across TN5000 seeds or BUSI/AUL folds. Mean AUC and Mean BalAcc are averaged over the three datasets.}",
        "    \\label{tab:complexity_performance}",
        "    \\resizebox{\\textwidth}{!}{%",
        "    \\begin{tabular}{lllccccccccc}",
        "        \\toprule",
        "        Method & Type & Input & Params (M)$\\downarrow$ & MACs (G)$\\downarrow$ & CUDA ms$\\downarrow$ & CUDA FPS$\\uparrow$ & \\multicolumn{3}{c}{AUC$\\uparrow$} & Mean AUC$\\uparrow$ & Mean BalAcc$\\uparrow$ \\\\",
        "        \\cmidrule(lr){8-10}",
        "        & & & & & & & TN5000 & BUSI & AUL & & \\\\",
        "        \\midrule",
    ]
    for row in rows:
        method = str(row["method"])
        display_method = method
        display_type = str(row["type"])
        tex_input = str(row["input"]).replace("x", r" \times ")
        display_input = f"${tex_input}$"
        params = f"{float(row['params_m']):.2f}"
        macs = f"{float(row['macs_g']):.2f}"
        cuda_ms = f"{float(row['cuda_ms']):.2f}"
        cuda_fps = f"{float(row['cuda_fps']):.1f}"
        tn_auc = bold_if_best(method, fmt(float(row["tn_auc"])), best_tn)
        busi_auc = bold_if_best(method, fmt(float(row["busi_auc"])), best_busi)
        aul_auc = bold_if_best(method, fmt(float(row["aul_auc"])), best_aul)
        mean_auc = bold_if_best(method, fmt(float(row["mean_auc"])), best_mean_auc)
        mean_balacc = bold_if_best(method, fmt(float(row["mean_balacc"])), best_mean_balacc)
        if method == "UL-TransXNet":
            display_method = "\\textbf{UL-TransXNet}"
            display_type = "\\textbf{Ours}"
            params = f"\\textbf{{{params}}}"
            macs = f"\\textbf{{{macs}}}"
        lines.append(
            f"        {display_method} & {display_type} & {display_input} & {params} & {macs} & {cuda_ms} & {cuda_fps} & {tn_auc} & {busi_auc} & {aul_auc} & {mean_auc} & {mean_balacc} \\\\"
        )
    lines.extend(
        [
            "        \\bottomrule",
            "    \\end{tabular}%",
            "    }",
            "\\end{table*}",
            "",
        ]
    )
    OUT_TEX.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    rows = build_rows()
    write_csv(rows)
    write_tex(rows)
    print(f"[SAVE] {OUT_CSV}")
    print(f"[SAVE] {OUT_TEX}")


if __name__ == "__main__":
    main()
